name: CD
on:
  release:
    types: [published]
  push:
    branches: [ lab4* ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: course.prafdin.ru
          username: user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 3119
          script: |
            cd /home/user/catty-reminders-app
            git fetch origin
            git reset --hard origin/lab4

            export APP_IMAGE=ghcr.io/demonstinatord/catty-reminders-app-app:${{ github.sha }}
            export DB_IMAGE=ghcr.io/demonstinatord/catty-reminders-app-db:${{ github.sha }}
	    export DEPLOY_REF=${{ github.sha }}
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose up -d --pull always --remove-orphans --force-recreate
            docker image prune -f
